DROP TABLE user_role PURGE;
DROP TABLE "Case_Test_Upper" PURGE;
DROP TABLE case_test_lower PURGE;
DROP TABLE array_types_annotation_test PURGE;
DROP TABLE binary_types_explicit_test PURGE;
DROP TABLE enum_types_explicit_test PURGE;
DROP TABLE time_types_explicit_test PURGE;
DROP TABLE json_types_explicit_test PURGE;
DROP TABLE basic_types_explicit_test PURGE;
DROP TABLE basic_types_test PURGE;
DROP TABLE array_types_explicit_test PURGE;
DROP TABLE array_types_test PURGE;
DROP TABLE test_special_types PURGE;
DROP TABLE complex_order PURGE;
DROP TABLE product_vector PURGE;
DROP TABLE user_order PURGE;
DROP TABLE user_info PURGE;
DROP SEQUENCE user_info_id_seq;

CREATE SEQUENCE user_info_id_seq START WITH 100000 INCREMENT BY 1;

CREATE TABLE user_role (
    user_id     NUMBER(10) NOT NULL,
    role_id     NUMBER(10) NOT NULL,
    role_name   VARCHAR2(100),
    create_time TIMESTAMP,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE user_info (
    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    age NUMBER(10),
    email VARCHAR2(100),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_order (
    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER(10),
    order_no VARCHAR2(100),
    amount NUMBER(10, 2),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_user_order_user_id ON user_order(user_id);

CREATE TABLE product_vector (
    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    embedding CLOB
);

CREATE TABLE complex_order (
    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_no VARCHAR2(100),
    address CLOB,
    items CLOB
);

CREATE TABLE basic_types_test (
    id           NUMBER(10) PRIMARY KEY,
    byte_value   NUMBER(3),
    short_value  NUMBER(5),
    int_value    NUMBER(10),
    long_value   NUMBER(19),
    float_value  BINARY_FLOAT,
    double_value BINARY_DOUBLE,
    decimal_value NUMBER(10, 2),
    big_int_value NUMBER(20),
    bool_value   NUMBER(1),
    string_value VARCHAR2(255),
    char_value   CHAR(1)
);

CREATE TABLE basic_types_explicit_test (
    id             NUMBER(10) PRIMARY KEY,
    byte_value     NUMBER(3),
    short_value    NUMBER(5),
    int_value      NUMBER(10),
    long_value     NUMBER(19),
    float_value    BINARY_FLOAT,
    double_value   BINARY_DOUBLE,
    decimal_value  NUMBER(10, 2),
    big_int_value  NUMBER(20),
    bool_bit       NUMBER(1),
    bool_boolean   NUMBER(1),
    char_value     CHAR(1),
    varchar_value  VARCHAR2(255),
    nvarchar_value NVARCHAR2(255)
);

CREATE TABLE array_types_test (
    id            NUMBER(10) PRIMARY KEY,
    int_array     CLOB,
    string_array  CLOB,
    float_array   CLOB
);

CREATE TABLE array_types_explicit_test (
    id            NUMBER(10) PRIMARY KEY,
    int_array     CLOB,
    varchar_array CLOB
);

CREATE TABLE array_types_annotation_test (
    id                      NUMBER(10) PRIMARY KEY,
    array_no_annotation     CLOB,
    array_jdbc_type         CLOB,
    array_type_handler      CLOB,
    array_number_special    CLOB,
    array_full_annotated    CLOB
);

CREATE TABLE test_special_types (
    id        NUMBER(10) PRIMARY KEY,
    json_map  CLOB,
    json_list CLOB,
    json_set  CLOB,
    int_array CLOB
);

CREATE TABLE binary_types_explicit_test (
    id                    NUMBER(10) PRIMARY KEY,
    binary_value          RAW(1000),
    varbinary_value       BLOB,
    longvarbinary_value   BLOB,
    blob_value            BLOB
);

CREATE TABLE enum_types_explicit_test (
    id               NUMBER(10) PRIMARY KEY,
    status_string    VARCHAR2(50),
    status_enum_code VARCHAR2(50),
    status_ordinal   NUMBER(10),
    status_code      NUMBER(10)
);

CREATE TABLE time_types_explicit_test (
    id                  NUMBER(10) PRIMARY KEY,
    date_value          DATE,
    time_value          TIMESTAMP,
    timestamp_value     TIMESTAMP,
    local_date_ts       TIMESTAMP,
    local_time_ts       TIMESTAMP,
    local_datetime_ts   TIMESTAMP,
    julian_day          NUMBER(19)
);

CREATE TABLE json_types_explicit_test (
    id           NUMBER(10) PRIMARY KEY,
    json_varchar VARCHAR2(2000),
    json_mysql   CLOB,
    nested_json  CLOB
);

CREATE TABLE case_test_lower (
    id          NUMBER(10) PRIMARY KEY,
    name        VARCHAR2(100),
    age         NUMBER(10),
    memo        VARCHAR2(200)
);

CREATE TABLE "Case_Test_Upper" (
    "Id"        NUMBER(10) PRIMARY KEY,
    "Name"      VARCHAR2(100),
    "Age"       NUMBER(10),
    "Memo"      VARCHAR2(200)
);
