version: '3.1'

# use this yml for docker-compose up -d
services:
  mysql:
    image: mysql:8.0.22
    environment:
      - MYSQL_DATABASE=devtester
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    ports:
      - 13306:3306
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time_zone='+8:00'
    # User/Password：root/123456
  mysql_7_7_18:
    image: mysql:5.7.18
    environment:
      - MYSQL_DATABASE=devtester
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    ports:
      - 13307:3306
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time_zone='+8:00'
    # User/Password：root/123456

  postgres:
    image: postgres:12.4
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - 15432:5432
    restart: always
    # User/Password：postgres/123456

  oracle_12c:
    image: truevoly/oracle-12c
    ports:
      - 11521:1521
      - 11522:8080
    restart: always
    # User/Password：system/oracle
    # WebConsole：http://192.168.0.164:50102/em/login（sys/oracle）
    # -- CREATE USER "TESTER" IDENTIFIED BY TESTER PROFILE "DEFAULT" ACCOUNT UNLOCK DEFAULT TABLESPACE  "USERS" TEMPORARY TABLESPACE "TEMP";
    # -- GRANT "DBA" TO "TESTER";

  mssql_2017:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Share123456!
      - ACCEPT_EULA=Y
    ports:
      - 11433:1433
    restart: always
    # User/Password：sa/Share123456!
    # https://hub.docker.com/_/microsoft-mssql-server?tab=description
    # https://mcr.microsoft.com/v2/mssql/server/tags/list

  db2:
    image: ibmcom/db2
    environment:
      - DB2INST1_PASSWORD=123456
      - DBNAME=devtesterdb
      - LICENSE=accept
    ports:
      - 50000:50000
    privileged: true
    restart: always
    # User/Password：db2inst1/123456
    # -v /usr/local/db2:/database
    # docker exec -it 85011f695773 /bin/bash
    # su - db2inst1
    # db2 list database directory
    # db2sampl
    #  登陆 SAMPLE 数据库

  clickhouse:
    image: clickhouse/clickhouse-server
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=root
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - TZ=Asia/Shanghai
      - CLICKHOUSE_PASSWORD=password123
    ports:
      - 18123:8123
      - 19000:9000
    # -v /var/local/apps/clickhouse/data:/var/lib/clickhouse
    #   --ulimit nofile=262144:262144
    restart: always

  redis:
    image: redis:7.2.3
    privileged: true
    ports:
      - 16379:6379
    # - /apps/redis/datadir:/data
    # - /apps/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    # - /apps/redis/logs:/logs
    restart: always
    command: redis-server --requirepass 123456

# 达梦
# https://download.dameng.com/eco/dm8/dm8_20230808_rev197096_x86_rh6_64_single.tar