plugins {
    id 'java-library'
    id 'maven-publish'
}

ext.pomName = 'dbVisitor-spring-starter'
description = 'Integrate dbVisitor and Spring Boot.'
dependencies {
    api project(':dbvisitor-spring')

    compileOnly 'org.springframework.boot:spring-boot-autoconfigure:2.7.3'
    compileOnly 'org.springframework.boot:spring-boot-starter-jdbc:2.7.3'
    compileOnly 'org.springframework:spring-beans:5.3.23'
}
