plugins {
    id 'java-library'
    id 'maven-publish'
    id 'antlr'
    id 'com.gradleup.shadow'
}

test {
    exclude '**/realdb/**'
}

ext.pomName = 'dbVisitor Adapter of Milvus'
description = 'JDBC driver adapter for Milvus.'

configurations {
    shaded
}

dependencies {
    api project(':dbvisitor-driver')
    api 'io.milvus:milvus-sdk-java:2.6.22'
    api 'com.fasterxml.jackson.core:jackson-databind:2.18.0'

    antlr "org.antlr:antlr4:${property('lib.antlr')}"
    compileOnly "org.antlr:antlr4-runtime:${property('lib.antlr')}"
    shaded "org.antlr:antlr4-runtime:${property('lib.antlr')}"
    testImplementation "org.antlr:antlr4-runtime:${property('lib.antlr')}"
    testImplementation 'org.slf4j:slf4j-api:1.7.32'
    testImplementation 'io.minio:minio:8.5.7'
    testImplementation 'org.powermock:powermock-module-junit4:2.0.9'
    testImplementation 'org.powermock:powermock-api-mockito2:2.0.9'
}

tasks.named('generateGrammarSource') {
    arguments += ['-visitor', '-package', 'net.hasor.dbvisitor.adapter.milvus.parser']
}

tasks.named('shadowJar') {
    configurations = [project.configurations.shaded]
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    relocate 'org.antlr', 'net.hasor.dbvisitor.adapter.milvus.internal.jars.antlr'
    exclude 'META-INF/maven/ognl/**'
    exclude 'META-INF/maven/org.javassist/**'
}
