/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    guides: [
        {
            type: 'autogenerated',
            dirName: 'guides',
        },
    ],
    drivers: [
        {
            type: 'category',
            label: '驱动适配介绍',
            link: {type: 'doc', id: 'drivers/about'},
            items: [
                'drivers/dev/about',
                'drivers/dev/guide',
                'drivers/limited',
            ],
        },
        {
            type: 'category',
            label: 'JDBC Elastic',
            link: {type: 'doc', id: 'drivers/elastic/about'},
            items: ['drivers/elastic/dependencies', 'drivers/elastic/connection', 'drivers/elastic/params', 'drivers/elastic/limitations'],
        },
        {
            type: 'category',
            label: 'JDBC Milvus',
            link: {type: 'doc', id: 'drivers/milvus/about'},
            items: ['drivers/milvus/dependencies', 'drivers/milvus/connection', 'drivers/milvus/params', 'drivers/milvus/execution', 'drivers/milvus/parameters', 'drivers/milvus/results', 'drivers/milvus/limitations'],
        },
        {
            type: 'category',
            label: 'JDBC Mongo',
            link: {type: 'doc', id: 'drivers/mongo/about'},
            items: ['drivers/mongo/dependencies', 'drivers/mongo/connection', 'drivers/mongo/params', 'drivers/mongo/limitations'],
        },
        {
            type: 'category',
            label: 'JDBC Redis',
            link: {type: 'doc', id: 'drivers/redis/about'},
            items: ['drivers/redis/dependencies', 'drivers/redis/connection', 'drivers/redis/params', 'drivers/redis/limitations'],
        },
    ],
    features: [
        {
            type: 'autogenerated',
            dirName: 'features',
        },
    ],
    releases: [
        {
            type: 'autogenerated',
            dirName: 'releases',
        },
    ]
};

module.exports = sidebars;
