plugins {
    id 'java-library'
    id 'maven-publish'
}

dependencies {
    api project(':dbvisitor')
    api 'org.springframework:spring-context:4.0.0.RELEASE'
    api 'org.springframework:spring-jdbc:4.0.0.RELEASE'
    api 'javax.annotation:javax.annotation-api:1.3.2'

    testImplementation 'org.springframework:spring-test:4.0.0.RELEASE'
    testImplementation 'mysql:mysql-connector-java:8.0.33'
    testImplementation 'com.zaxxer:HikariCP:4.0.3'
}
