plugins {
    id 'java-library'
    id 'maven-publish'
}

ext.pomName = 'dbVisitor-spring'
description = 'Integrate dbVisitor and Spring.'

dependencies {
    api project(':dbvisitor')
    api 'org.springframework:spring-context:4.0.0.RELEASE'
    api 'org.springframework:spring-jdbc:4.0.0.RELEASE'
    api 'javax.annotation:javax.annotation-api:1.3.2'

    testImplementation 'org.springframework:spring-test:4.0.0.RELEASE'
    testImplementation 'com.h2database:h2:2.2.224'
    testImplementation 'com.zaxxer:HikariCP:4.0.3'
}
