/* https://eco.dameng.com/document/dm/zh-cn/pm/dm8_sql-data-types-operators.html */
create table tb_dm8_types
(
    c_id                         bigint primary key,
    c_char                       char,
    c_char_n                     char(12),
    c_char_nb                    char(12 byte) ,
    c_char_nc                    char(12 char),
    c_character                  character(10),
    c_character_b                character(10 byte),
    c_character_c                character(10 char),

    c_nchar_n                    nchar(12),
    c_national_character         national character(12),
    c_national_char              national char(12),

    c_varchar                    varchar(24),
    c_varchar_b                  varchar(24 byte),
    c_varchar_c                  varchar(24 char),

    c_varchar2                   varchar2(24),
    c_varchar2_b                 varchar2(24 byte),
    c_varchar2_c                 varchar2(24 char),
    c_character_varying          character varying(24),
    c_character_varying_b        character varying(24 byte),
    c_character_varying_c        character varying(24 char),
    c_char_varying               char varying(24),
    c_char_varying_b             char varying(24 byte),
    c_char_varying_c             char varying(24 char),
    c_national_char_varying      national char varying(24),

    c_nvarchar2                  nvarchar2(24),
    c_national_character_varying national character varying(24),
    c_nchar_varying              nchar varying(24),

    c_clob                       clob,
    c_nclob                      nclob,
    c_text                       text,
    c_long                       long,
    c_longvarchar                longvarchar,

    c_number                     number,
    c_number_n                   number(10),
    c_number_n_n                 number(10, 2),
    c_numeric                    numeric,
    c_numeric_n                  numeric(10),
    c_numeric_n_n                numeric(*, 2),
    c_decimal                    decimal,
    c_decimal_n                  decimal(10),
    c_decimal_n_n                decimal(10, 2),
    c_dec                        dec,
    c_dec_n                      dec(10),
    c_dec_n_n                    dec(10, 2),

    c_float                      float,
    c_float_n                    float(10),
    c_integer                    integer,
    c_int                        int,
    c_tinyint                    tinyint,
    c_byte                       byte,
    c_smallint                   smallint,
    c_bitint                     bigint,
    c_double_p                   double precision,
    c_real                       real,

    c_bfloat                     binary_float,
    c_bdouble                    binary_double,

    c_binary                     binary,
    c_varbinary                  varbinary,
    c_binary_n                   binary(20),
    c_varbinary_n                varbinary(20),
    c_image                      image,
    c_longvarbinary              longvarbinary,
    c_blob                       blob,
    c_bfile                      bfile,

    c_bit                        bit,

    c_date                       date,
    c_time                       time,
    c_time_n                     time(3),
    c_time_tz                    time with time zone,
    c_time_tz_n                  time(3) with time zone,
    c_timestamp                  timestamp,
    c_timestamp_n                timestamp(6),
    c_timestamp_z                timestamp with time zone,
    c_timestamp_n_z              timestamp(6) with time zone,
    c_timestamp_lz               timestamp with local time zone,
    c_timestamp_n_lz             timestamp(6) with local time zone,
    c_interval_year              interval year,
    c_interval_year_n            interval year(9),
    c_interval_year_month        interval year to month,
    c_interval_year_month_n      interval year(9) to month,
    c_interval_month             interval month,
    c_interval_month_n           interval month(9),
    c_interval_day               interval day,
    c_interval_day_n             interval day(9),
    c_interval_day_hour          interval day to hour,
    c_interval_day_hour_n        interval day(9) to hour,
    c_interval_day_minute        interval day to minute,
    c_interval_day_minute_n      interval day(9) to minute,
    c_interval_day_second        interval day to second,
    c_interval_day_second_0_n    interval day to second(6),
    c_interval_day_second_n      interval day(9) to second,
    c_interval_day_second_n_n    interval day(9) to second(6),
    c_interval_hour              interval hour,
    c_interval_hour_n            interval hour(2),
    c_interval_hour_minute       interval hour to minute,
    c_interval_hour_minute_n     interval hour(2) to minute,
    c_interval_hour_sec_00       interval hour to second,
    c_interval_hour_sec_n0       interval hour(2) to second,
    c_interval_hour_sec_nn       interval hour(2) to second(6),
    c_interval_hour_sec_0n       interval hour to second(6),
    c_interval_minute            interval minute,
    c_interval_minute_n          interval minute(2),
    c_interval_minute_sec_00     interval minute to second,
    c_interval_minute_sec_n0     interval minute(2) to second,
    c_interval_minute_sec_nn     interval minute(2) to second(6),
    c_interval_minute_sec_0n     interval minute to second(6),
    c_interval_sec               interval second,
    c_interval_sec_n             interval second(6),
    c_interval_sec_nn            interval second(6,3),

    c_xml                        xmltype
);