/* http://www.h2database.com/html/datatypes.html */
create table tb_h2_types
(
    id                       bigint auto_increment primary key,
    c_char                   character(20),
    c_varchar                character varying,
    c_char_lage              character large object,
    c_char_case              varchar_ignorecase,
    --
    c_binary                 binary,
    c_varbinary              binary varying,
    c_binary_lage            binary large object,
    --
    c_boolean                boolean,
    --
    c_tinyint                tinyint,
    c_smallint               smallint,
    c_int                    int,
    c_integer                integer,
    c_bigint                 bigint,
    c_numeric_10             numeric(20, 10),
    c_numeric_2              numeric(20, 2),
    c_real                   real,
    c_double                 double precision,
    c_decfloat               decfloat,
    --
    c_date                   date,
    c_time                   time,
    c_tiimetz                time with time zone,
    c_timestamp              timestamp,
    c_timestamptz            timestamp(9) with time zone,
    c_interval_year          interval year,
    c_interval_month         interval month,
    c_interval_day           interval day,
    c_interval_hour          interval hour,
    c_interval_minute        interval minute,
    c_interval_second        interval second,
    c_interval_year_month    interval year to month,
    c_interval_day_hour      interval day to hour,
    c_interval_day_minute    interval day to minute,
    c_interval_day_second    interval day to second,
    c_interval_hour_minute   interval hour to minute,
    c_interval_hour_second   interval hour to second,
    c_interval_minute_second interval minute to second,
    c_object                 java_object,
    c_enum                   enum ('a','b','c'),
    c_geometry               geometry,
    c_json                   json,
    c_uuid                   uuid,
    a_char                   char array,
    a_object                 java_object array
);
