/*
 * Copyright 2015-2022 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0.
 * See the LICENSE.txt file for the full license.
 * https://www.apache.org/licenses/LICENSE-2.0
 */
package net.hasor.dbvisitor.test.realdb.milvus;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.UUID;
import net.hasor.dbvisitor.jdbc.core.JdbcTemplate;
import net.hasor.dbvisitor.lambda.LambdaTemplate;
import net.hasor.dbvisitor.test.contract.api.adapter.AdapterContractTest;
import net.hasor.dbvisitor.test.contract.material.model.keygen.KeyUuid32User;
import net.hasor.dbvisitor.test.contract.material.model.keygen.KeyUuid36User;
import net.hasor.dbvisitor.test.contract.material.model.keygen.KeyUuidStringUser;
import net.hasor.dbvisitor.test.nxn.capability.Capability;
import net.hasor.dbvisitor.test.nxn.capability.CapabilityId;
import net.hasor.dbvisitor.test.nxn.env.DataSourceProfile;
import net.hasor.dbvisitor.test.nxn.env.MilvusProfile;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

/** UUIDs are generated by dbVisitor before INSERT, not by Milvus AutoID or a sequence. */
public class MilvusClientKeysSqlContractTest extends AdapterContractTest {
    private final MilvusUserInfoFixture fixture = new MilvusUserInfoFixture();
    private Connection connection;
    private LambdaTemplate lambda;

    @Override
    protected DataSourceProfile profile() {
        return MilvusProfile.INSTANCE;
    }

    @Before
    public void openFixture() throws SQLException {
        this.connection = this.fixture.open();
        this.jdbcTemplate = new JdbcTemplate(this.connection);
        this.lambda = new LambdaTemplate(this.connection);
    }

    @After
    public void closeFixture() throws SQLException {
        try {
            if (this.connection != null) {
                try (Statement statement = this.connection.createStatement()) {
                    statement.executeUpdate("DROP TABLE IF EXISTS user_uuid");
                }
            }
        } finally {
            this.fixture.close();
        }
    }

    @Test
    @Capability(CapabilityId.ADAPTER_MILVUS_CLIENT_UUID_FIELDS)
    public void uuidFieldsShouldBePopulatedAndPersistedUsingSharedEntities() throws SQLException {
        KeyUuid32User first = new KeyUuid32User();
        first.setId(1);
        KeyUuid32User second = new KeyUuid32User();
        second.setId(2);
        assertEquals(2, this.lambda.insert(KeyUuid32User.class).applyEntity(List.of(first, second)).executeSumResult());
        assertTrue(first.getName().matches("[0-9a-f]{32}"));
        assertTrue(second.getName().matches("[0-9a-f]{32}"));
        assertNotEquals(first.getName(), second.getName());
        assertEquals(first.getName(), this.jdbcTemplate.queryForString("SELECT name FROM user_info WHERE id=1"));
        assertEquals(second.getName(), this.jdbcTemplate.queryForString("SELECT name FROM user_info WHERE id=2"));
        KeyUuid36User third = new KeyUuid36User();
        third.setId(3);
        assertEquals(1, this.lambda.insert(KeyUuid36User.class).applyEntity(third).executeSumResult());
        assertEquals(UUID.fromString(third.getName()).toString(), third.getName());
        assertEquals(third.getName(), this.jdbcTemplate.queryForString("SELECT name FROM user_info WHERE id=3"));
    }

    @Test
    @Capability(CapabilityId.ADAPTER_MILVUS_CLIENT_UUID_PRIMARY_KEY)
    public void generatedStringPrimaryKeyShouldSupportNativeReadUpdateAndDelete() throws SQLException {
        this.jdbcTemplate.executeUpdate("""
                CREATE TABLE user_uuid (
                    id VARCHAR(36) PRIMARY KEY, name VARCHAR(128) NULL, age INT32 NULL, create_time VARCHAR(128) NULL,
                    vector_text VARCHAR(128) DEFAULT 'fixture' WITH (enable_analyzer=true),
                    v SPARSE_FLOAT_VECTOR, FUNCTION fixture_vector USING BM25 (vector_text) INTO (v)
                ) WITH (consistency_level=Strong)
                """);
        this.jdbcTemplate.executeUpdate("CREATE INDEX uuid_v ON user_uuid(v) USING SPARSE_INVERTED_INDEX WITH (metric_type=BM25)");
        this.jdbcTemplate.executeUpdate("LOAD TABLE user_uuid");
        KeyUuidStringUser user = new KeyUuidStringUser();
        user.setName("generated");
        assertEquals(1, this.lambda.insert(KeyUuidStringUser.class).applyEntity(user).executeSumResult());
        assertEquals(UUID.fromString(user.getId()).toString(), user.getId());
        assertEquals("generated", this.lambda.query(KeyUuidStringUser.class).eq(KeyUuidStringUser::getId, user.getId()).queryForObject().getName());
        assertEquals(1, this.lambda.update(KeyUuidStringUser.class).eq(KeyUuidStringUser::getId, user.getId())
                .updateTo(KeyUuidStringUser::getName, "updated").doUpdate());
        assertEquals("updated", this.jdbcTemplate.queryForString("SELECT name FROM user_uuid WHERE id=?", user.getId()));
        assertEquals(1, this.lambda.delete(KeyUuidStringUser.class).eq(KeyUuidStringUser::getId, user.getId()).doDelete());
        assertNull(this.lambda.query(KeyUuidStringUser.class).eq(KeyUuidStringUser::getId, user.getId()).queryForObject());
    }
}
