/*
 * Copyright 2015-2022 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0.
 * See the LICENSE.txt file for the full license.
 * https://www.apache.org/licenses/LICENSE-2.0
 */
package net.hasor.dbvisitor.test.scenario;

import java.sql.Timestamp;
import java.util.List;
import java.util.Map;
import net.hasor.dbvisitor.session.Configuration;
import net.hasor.dbvisitor.session.Session;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

public abstract class ReturningScenario extends net.hasor.dbvisitor.test.nxn.junit.AbstractNxnContractTest {
    protected abstract String insertSql();
    protected abstract String updateSql();
    protected abstract String deleteSql();

    private void prepareTable() throws Exception {
        dropTableIfExists("doc_returning");
        String identity = profile().env().equals("mssql") ? "IDENTITY(1, 1)" : "GENERATED BY DEFAULT AS IDENTITY";
        String timestamp = profile().env().equals("mssql") ? "DATETIME2 DEFAULT SYSDATETIME()" : "TIMESTAMP DEFAULT CURRENT_TIMESTAMP";
        jdbcTemplate.executeUpdate("CREATE TABLE doc_returning (id BIGINT " + identity
                + " PRIMARY KEY, name VARCHAR(64), age INTEGER, create_time " + timestamp + ")");
    }

    @Test
    public void insertUpdateDelete_returnFieldsAndEmptyResultWhenMissing() throws Exception {
        prepareTable();
        try {
            Map<String, Object> saved = jdbcTemplate.queryForMap(insertSql(), new Object[] { "mali", 18 });
            Long id = ((Number) saved.get("id")).longValue();
            assertNotNull(saved.get("create_time"));
            List<Map<String, Object>> changed = jdbcTemplate.queryForList(updateSql(), new Object[] { 19, id });
            assertEquals(1, changed.size());
            assertEquals(19, ((Number) changed.get(0).get("age")).intValue());
            assertEquals(Integer.valueOf(19), jdbcTemplate.queryForObject("SELECT age FROM doc_returning WHERE id = ?", new Object[] { id }, Integer.class));
            List<Map<String, Object>> deleted = jdbcTemplate.queryForList(deleteSql(), new Object[] { id });
            assertEquals("mali", deleted.get(0).get("name"));
            assertTrue(jdbcTemplate.queryForList(updateSql(), new Object[] { 20, id }).isEmpty());
            assertTrue(jdbcTemplate.queryForList(deleteSql(), new Object[] { id }).isEmpty());
            assertEquals(Integer.valueOf(0), jdbcTemplate.queryForObject("SELECT COUNT(*) FROM doc_returning", Integer.class));
        } finally {
            dropTableIfExists("doc_returning");
        }
    }

    @Test
    public void xmlResultSet_backfillsIdentityAndDefaultTimestamp() throws Exception {
        prepareTable();
        try {
            Configuration config = new Configuration();
            config.loadMapper("realdb/" + profile().env() + "/material/ReturningScenarioMapper.xml");
            SavedUser user = new SavedUser();
            user.setName("mali");
            user.setAge(18);
            try (Session session = config.newSession(dataSource)) {
                session.executeStatement("doc.returning.insertUser", user);
            }
            assertNotNull(user.getId());
            assertNotNull(user.getCreateTime());
            assertEquals(user.getCreateTime(), jdbcTemplate.queryForObject("SELECT create_time FROM doc_returning WHERE id = ?", new Object[] { user.getId() }, Timestamp.class));
        } finally {
            dropTableIfExists("doc_returning");
        }
    }

    public static class SavedUser {
        private Long id;
        private String name;
        private Integer age;
        private Timestamp createTime;

        public Long getId() {
            return this.id;
        }

        public void setId(Long id) {
            this.id = id;
        }

        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public Integer getAge() {
            return this.age;
        }

        public void setAge(Integer age) {
            this.age = age;
        }

        public Timestamp getCreateTime() {
            return this.createTime;
        }

        public void setCreateTime(Timestamp createTime) {
            this.createTime = createTime;
        }

    }
}
