ALTER SESSION SET CONTAINER = DEVTESTDB;

ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED;
ALTER USER devtester IDENTIFIED BY "123456" ACCOUNT UNLOCK;
GRANT CREATE MATERIALIZED VIEW TO devtester;
GRANT CREATE SYNONYM TO devtester;
GRANT CREATE TYPE TO devtester;
GRANT CREATE DATABASE LINK TO devtester;
