version: '3.1'

services:
  oracle_12c:
    image: truevoly/oracle-12c
    ports:
      - 11521:1521
      - 11522:8080
    restart: always
    # User/Password：system/oracle
    # WebConsole：http://127.0.0.1:11522/em/login（sys/oracle）
