#!/usr/bin/env bash
set -euo pipefail

NET_ADMIN="${ORACLE_BASE_HOME}/network/admin"
WALLET_DIR="${ORACLE_BASE}/oradata/dbconfig/${ORACLE_SID}/wallet"
MTLS_ADMIN="${ORACLE_BASE}/oradata/dbconfig/${ORACLE_SID}/mtls-admin"

mkdir -p "${WALLET_DIR}"
cp /wallet/cwallet.sso /wallet/ewallet.p12 "${WALLET_DIR}/"
chmod 600 "${WALLET_DIR}/cwallet.sso" "${WALLET_DIR}/ewallet.p12"

cat > "${NET_ADMIN}/listener.ora" <<EOF
LISTENER =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC_FOR_${ORACLE_SID}))
      (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1521))
      (ADDRESS = (PROTOCOL = TCPS)(HOST = 0.0.0.0)(PORT = 2484))
    )
  )

WALLET_LOCATION =
  (SOURCE =
    (METHOD = FILE)
    (METHOD_DATA =
      (DIRECTORY = ${WALLET_DIR})
    )
  )

SSL_CLIENT_AUTHENTICATION = FALSE
DEFAULT_SERVICE_LISTENER = ${ORACLE_SID}
EOF

cat > "${NET_ADMIN}/sqlnet.ora" <<EOF
NAMES.DIRECTORY_PATH = (EZCONNECT, TNSNAMES)
DISABLE_OOB = ON
BREAK_POLL_SKIP = 1000

WALLET_LOCATION =
  (SOURCE =
    (METHOD = FILE)
    (METHOD_DATA =
      (DIRECTORY = ${WALLET_DIR})
    )
  )

SSL_CLIENT_AUTHENTICATION = FALSE
SSL_VERSION = 1.2
EOF

mkdir -p "${MTLS_ADMIN}"
cat > "${MTLS_ADMIN}/listener.ora" <<EOF
LISTENER_MTLS =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCPS)(HOST = 0.0.0.0)(PORT = 2485))
    )
  )

SID_LIST_LISTENER_MTLS =
  (SID_LIST =
    (SID_DESC =
      (GLOBAL_DBNAME = DEVTESTDB)
      (ORACLE_HOME = ${ORACLE_HOME})
      (SID_NAME = ${ORACLE_SID})
    )
  )

WALLET_LOCATION =
  (SOURCE =
    (METHOD = FILE)
    (METHOD_DATA =
      (DIRECTORY = ${WALLET_DIR})
    )
  )

SSL_CLIENT_AUTHENTICATION = TRUE
DEFAULT_SERVICE_LISTENER_MTLS = ${ORACLE_SID}
EOF

cat > "${MTLS_ADMIN}/sqlnet.ora" <<EOF
NAMES.DIRECTORY_PATH = (EZCONNECT, TNSNAMES)
DISABLE_OOB = ON
BREAK_POLL_SKIP = 1000

WALLET_LOCATION =
  (SOURCE =
    (METHOD = FILE)
    (METHOD_DATA =
      (DIRECTORY = ${WALLET_DIR})
    )
  )

SSL_CLIENT_AUTHENTICATION = TRUE
SSL_VERSION = 1.2
EOF

lsnrctl stop
lsnrctl start
TNS_ADMIN="${MTLS_ADMIN}" lsnrctl stop LISTENER_MTLS || true
TNS_ADMIN="${MTLS_ADMIN}" lsnrctl start LISTENER_MTLS
sqlplus -s / as sysdba <<'EOF'
ALTER SYSTEM REGISTER;
ALTER SESSION SET CONTAINER = DEVTESTDB;
ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED;
ALTER USER devtester IDENTIFIED BY "123456" ACCOUNT UNLOCK;
EXIT;
EOF
