/*
 * Copyright 2015-2022 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0.
 * See the LICENSE.txt file for the full license.
 * https://www.apache.org/licenses/LICENSE-2.0
 */
package net.hasor.dbvisitor.lambda;
import java.sql.SQLException;
import java.sql.Connection;
import java.util.Map;
import net.hasor.dbvisitor.dialect.BoundSql;
import net.hasor.dbvisitor.jdbc.core.JdbcTemplate;
import net.hasor.dbvisitor.mapping.KeyType;
import net.hasor.dbvisitor.mapping.Column;
import net.hasor.dbvisitor.mapping.Table;
import org.junit.Test;
import net.hasor.test.utils.DsUtils;
import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertNotNull;

public class QueryResetTest {
    @Test
    public void insertReset_shouldDiscardOldRowsAndKeepMappedTarget() throws SQLException {
        var template = new LambdaTemplate();
        var insert = template.insert(ResetRow.class).applyMap(Map.of("id", 1, "name", "old"));
        insert.getBoundSql();
        assertSameCommand(template.insert(ResetRow.class).applyMap(Map.of("id", 2, "name", "new")).getBoundSql(),
                insert.reset().applyMap(Map.of("id", 2, "name", "new")).getBoundSql());
    }

    @Test
    public void freedomInsertReset_shouldDiscardOldRowsAndColumns() throws SQLException {
        var template = new LambdaTemplate();
        var insert = template.insertFreedom("app", "sales", "customers").applyMap(Map.of("id", 1, "obsolete", "old"));
        insert.getBoundSql();
        assertSameCommand(template.insertFreedom("app", "sales", "customers").applyMap(Map.of("id", 2, "name", "new")).getBoundSql(),
                insert.reset().applyMap(Map.of("id", 2, "name", "new")).getBoundSql());
    }

    @Test
    public void insertReset_shouldNotFillKeysIntoPreviouslyUsedEntities() throws SQLException {
        try (Connection connection = DsUtils.h2Conn()) {
            JdbcTemplate jdbc = new JdbcTemplate(connection);
            jdbc.execute("CREATE TABLE reset_generated (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(50))");
            try {
                var template = new LambdaTemplate(connection);
                GeneratedRow first = new GeneratedRow();
                first.name = "first";
                var insert = template.insert(GeneratedRow.class).applyEntity(first);
                assertEquals(1, insert.executeSumResult());
                Long originalKey = first.id;
                assertNotNull(originalKey);

                GeneratedRow discarded = new GeneratedRow();
                discarded.name = "discarded";
                insert.reset().applyEntity(discarded);
                insert.getBoundSql();
                GeneratedRow second = new GeneratedRow();
                second.name = "second";
                assertEquals(1, insert.reset().applyEntity(second).executeSumResult());
                assertEquals(originalKey, first.id);
                assertNull(discarded.id);
                assertNotNull(second.id);
                assertEquals(Long.valueOf(2), jdbc.queryForObject("SELECT COUNT(*) FROM reset_generated", Long.class));
            } finally {
                jdbc.execute("DROP TABLE reset_generated");
            }
        }
    }

    @Test
    public void mappedSelectReset_shouldKeepTargetAndDiscardOldClauses() throws SQLException {
        var template = new LambdaTemplate();
        var query = template.query(ResetRow.class).eq("id", 1).asc("name").initPage(10, 0);
        BoundSql actual = query.reset().eq("id", 2).desc("name").getBoundSql();
        BoundSql expected = template.query(ResetRow.class).eq("id", 2).desc("name").getBoundSql();
        assertSameCommand(expected, actual);
    }

    @Test
    public void mappedUpdateReset_shouldKeepTargetAndDiscardOldAssignments() throws SQLException {
        var template = new LambdaTemplate();
        var update = template.update(ResetRow.class).eq("id", 1).updateTo(ResetRow::getName, "old");
        BoundSql actual = update.reset().eq("id", 2).updateTo(ResetRow::getName, "new").getBoundSql();
        BoundSql expected = template.update(ResetRow.class).eq("id", 2).updateTo(ResetRow::getName, "new").getBoundSql();
        assertSameCommand(expected, actual);
    }

    @Test
    public void mappedDeleteReset_shouldKeepTargetAndDiscardOldConditions() throws SQLException {
        var template = new LambdaTemplate();
        var delete = template.delete(ResetRow.class).eq("id", 1);
        assertSameCommand(template.delete(ResetRow.class).eq("id", 2).getBoundSql(), delete.reset().eq("id", 2).getBoundSql());
    }

    @Test
    public void freedomReset_shouldKeepExplicitCatalogSchemaAndTable() throws SQLException {
        var template = new LambdaTemplate();
        var query = template.queryFreedom("app", "sales", "customers").eq("id", 1).asc("name");
        assertSameCommand(template.queryFreedom("app", "sales", "customers").eq("id", 2).getBoundSql(),
                query.reset().eq("id", 2).getBoundSql());
        var update = template.updateFreedom("app", "sales", "customers").eq("id", 1).updateTo("name", "old");
        assertSameCommand(template.updateFreedom("app", "sales", "customers").eq("id", 2).updateTo("name", "new").getBoundSql(),
                update.reset().eq("id", 2).updateTo("name", "new").getBoundSql());
        var delete = template.deleteFreedom("app", "sales", "customers").eq("id", 1);
        assertSameCommand(template.deleteFreedom("app", "sales", "customers").eq("id", 2).getBoundSql(),
                delete.reset().eq("id", 2).getBoundSql());
    }

    private static void assertSameCommand(BoundSql expected, BoundSql actual) {
        assertEquals(expected.getSqlString(), actual.getSqlString());
        assertArrayEquals(expected.getArgs(), actual.getArgs());
    }

    @Table(value = "customers", catalog = "app", schema = "sales")
    public static class ResetRow {
        @Column("id")
        private Integer id;
        @Column("name")
        private String name;

        public Integer getId() {
            return this.id;
        }

        public String getName() {
            return this.name;
        }
    }

    @Table("reset_generated")
    public static class GeneratedRow {
        @Column(value = "id", primary = true, keyType = KeyType.Auto)
        private Long id;
        @Column("name")
        private String name;

        public Long getId() {
            return this.id;
        }

        public void setId(Long id) {
            this.id = id;
        }

        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
    }
}
