/*
 * Copyright 2015-2022 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0.
 * See the LICENSE.txt file for the full license.
 * https://www.apache.org/licenses/LICENSE-2.0
 */
package net.hasor.dbvisitor.test.contract.feature.keygen;

import java.sql.SQLException;
import java.util.Date;

import net.hasor.dbvisitor.dialect.SqlDialect;
import net.hasor.dbvisitor.dialect.provider.Db2Dialect;
import net.hasor.dbvisitor.dialect.provider.H2Dialect;
import net.hasor.dbvisitor.dialect.provider.OracleDialect;
import net.hasor.dbvisitor.dialect.provider.PostgreSqlDialect;
import net.hasor.dbvisitor.dialect.provider.SqlServerDialect;
import net.hasor.dbvisitor.test.contract.material.model.keygen.KeyAutoUser;
import net.hasor.dbvisitor.test.contract.material.model.keygen.KeyNoneUser;
import net.hasor.dbvisitor.test.contract.material.model.keygen.KeySequenceUser;
import net.hasor.dbvisitor.test.contract.material.model.keygen.KeyUuid32User;
import net.hasor.dbvisitor.test.nxn.junit.AbstractNxnContractTest;

public abstract class KeyGenerationSupport extends AbstractNxnContractTest {

    protected void ensureStrictNoneTable() throws SQLException {
        dropTableIfExists("user_strict_none");
        jdbcTemplate.executeUpdate("CREATE TABLE user_strict_none (id INT NOT NULL PRIMARY KEY, name VARCHAR(255), age INT, create_time " + profile().datetimeColumnType() + ")");
    }

    protected void ensureAutoTable() throws SQLException {
        dropTableIfExists("user_keygen_auto");
        if (isMsSql()) {
            resetSequence("user_keygen_auto_seq", 1);
        }
        jdbcTemplate.executeUpdate("CREATE TABLE user_keygen_auto (id " + autoIntPrimaryKey("user_keygen_auto_seq") + ", name VARCHAR(255), age INT, create_time " + profile().datetimeColumnType() + ")");
    }

    protected void ensureAutoLongTable() throws SQLException {
        dropTableIfExists("user_keygen_auto_long");
        if (isMsSql()) {
            resetSequence("user_keygen_auto_long_seq", 1);
        }
        jdbcTemplate.executeUpdate("CREATE TABLE user_keygen_auto_long (id " + autoLongPrimaryKey() + ", name VARCHAR(255), age INT, create_time " + profile().datetimeColumnType() + ")");
    }

    protected void ensureAfterTable() throws SQLException {
        dropTableIfExists("user_keygen_after");
        if (isMsSql()) {
            resetSequence("user_keygen_after_seq", 1);
        }
        jdbcTemplate.executeUpdate("CREATE TABLE user_keygen_after (id " + autoIntPrimaryKey("user_keygen_after_seq") + ", name VARCHAR(255), age INT, create_time " + profile().datetimeColumnType() + ")");
    }

    protected void ensureUuidStringTable() throws SQLException {
        dropTableIfExists("user_uuid");
        jdbcTemplate.executeUpdate("CREATE TABLE user_uuid (id VARCHAR(36) NOT NULL PRIMARY KEY, name VARCHAR(100), age INT, create_time " + profile().datetimeColumnType() + ")");
    }

    protected String autoIntPrimaryKey(String sequenceName) {
        switch (profile().id()) {
            case MYSQL:
                return "INT AUTO_INCREMENT PRIMARY KEY";
            case PG:
                return "SERIAL PRIMARY KEY";
            case H2:
                return "INT AUTO_INCREMENT PRIMARY KEY";
            case MSSQL:
                return "INT PRIMARY KEY DEFAULT NEXT VALUE FOR " + sequenceName;
            case ORACLE:
                return "NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY";
            case DB2:
                return "INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
            default:
                return "INT PRIMARY KEY";
        }
    }

    protected String autoLongPrimaryKey() {
        switch (profile().id()) {
            case MYSQL:
                return "BIGINT AUTO_INCREMENT PRIMARY KEY";
            case PG:
                return "BIGSERIAL PRIMARY KEY";
            case H2:
                return "BIGINT AUTO_INCREMENT PRIMARY KEY";
            case MSSQL:
                return "BIGINT PRIMARY KEY DEFAULT NEXT VALUE FOR user_keygen_auto_long_seq";
            case ORACLE:
                return "NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY";
            case DB2:
                return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
            default:
                return "BIGINT PRIMARY KEY";
        }
    }

    protected void resetSequence(String seqName, int startWith) throws SQLException {
        dropSequenceIfExists(seqName);
        jdbcTemplate.executeUpdate("CREATE SEQUENCE " + seqName + " START WITH " + startWith + " INCREMENT BY 1");
    }

    protected SqlDialect sequenceDialect() {
        switch (profile().id()) {
            case H2:
                return H2Dialect.DEFAULT;
            case PG:
                return PostgreSqlDialect.DEFAULT;
            case ORACLE:
                return OracleDialect.DEFAULT;
            case DB2:
                return Db2Dialect.DEFAULT;
            case MSSQL:
                return SqlServerDialect.DEFAULT;
            default:
                throw new IllegalStateException("Sequence is unsupported by " + profile().env());
        }
    }

    protected KeySequenceUser sequenceUser(String name, int age) {
        KeySequenceUser user = new KeySequenceUser();
        user.setName(name);
        user.setAge(age);
        user.setCreateTime(new Date());
        return user;
    }

    protected KeyAutoUser autoUser(String name, int age) {
        KeyAutoUser user = new KeyAutoUser();
        user.setName(name);
        user.setAge(age);
        user.setCreateTime(new Date());
        return user;
    }

    protected KeyUuid32User uuid32User(int id, int age) {
        KeyUuid32User user = new KeyUuid32User();
        user.setId(id);
        user.setAge(age);
        user.setCreateTime(new Date());
        return user;
    }

    protected KeyNoneUser noneUser(int id, String name, int age) {
        KeyNoneUser user = new KeyNoneUser();
        user.setId(id);
        user.setName(name);
        user.setAge(age);
        user.setCreateTime(new Date());
        return user;
    }

    protected void deleteUserInfoIds(int first, int second) throws SQLException {
        jdbcTemplate.executeUpdate("DELETE FROM user_info WHERE id IN (?, ?)", new Object[] { first, second });
    }
}
