plugins {
    id 'java-library'
    id 'maven-publish'
}

ext.pomName = 'dbvisitor-solon-plugin'
description = 'Integrate dbVisitor and Solon.'

dependencies {
    api project(':dbvisitor')
    api 'org.noear:solon-data:3.0.7'

    testImplementation 'com.zaxxer:HikariCP:4.0.3'
    testImplementation 'com.h2database:h2:2.2.224'
    testImplementation 'ch.qos.logback:logback-classic:1.4.7'
    testImplementation 'org.noear:solon-test-junit4:3.0.7'
}
