DROP TABLE user_role;
DROP TABLE basic_types_explicit_test;
DROP TABLE basic_types_test;
DROP TABLE binary_types_explicit_test;
DROP TABLE enum_types_explicit_test;
DROP TABLE time_types_explicit_test;
DROP TABLE json_types_explicit_test;
DROP TABLE array_types_annotation_test;
DROP TABLE array_types_explicit_test;
DROP TABLE array_types_test;
DROP TABLE test_special_types;
DROP TABLE complex_order;
DROP TABLE product_vector;
DROP TABLE user_order;
DROP TABLE user_info;
DROP SEQUENCE user_info_id_seq;
DROP SEQUENCE user_order_id_seq;

CREATE TABLE user_role (
    user_id     INT NOT NULL,
    role_id     INT NOT NULL,
    role_name   VARCHAR(100),
    create_time TIMESTAMP,
    PRIMARY KEY (user_id, role_id)
);

CREATE SEQUENCE user_info_id_seq START WITH 100000 INCREMENT BY 1;

CREATE TABLE user_info (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    age INT,
    email VARCHAR(100),
    create_time TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

CREATE SEQUENCE user_order_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE user_order (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    order_no VARCHAR(100),
    amount DECIMAL(10, 2),
    create_time TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

CREATE INDEX idx_user_order_user_id ON user_order(user_id);

CREATE TABLE product_vector (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    embedding CLOB
);

CREATE TABLE complex_order (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(100),
    address CLOB,
    items CLOB
);

CREATE TABLE basic_types_test (
    id           INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    byte_value   SMALLINT,
    short_value  SMALLINT,
    int_value    INT,
    long_value   BIGINT,
    float_value  REAL,
    double_value DOUBLE,
    decimal_value DECIMAL(10, 2),
    big_int_value DECIMAL(20, 0),
    bool_value   BOOLEAN,
    string_value VARCHAR(255),
    char_value   CHAR(1)
);

CREATE TABLE basic_types_explicit_test (
    id             INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    byte_value     SMALLINT,
    short_value    SMALLINT,
    int_value      INT,
    long_value     BIGINT,
    float_value    REAL,
    double_value   DOUBLE,
    decimal_value  DECIMAL(10, 2),
    big_int_value  DECIMAL(20, 0),
    bool_bit       BOOLEAN,
    bool_boolean   BOOLEAN,
    char_value     CHAR(1),
    varchar_value  VARCHAR(255),
    nvarchar_value VARCHAR(255)
);

CREATE TABLE array_types_test (
    id            INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    int_array     CLOB,
    string_array  CLOB,
    float_array   CLOB
);

CREATE TABLE array_types_explicit_test (
    id            INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    int_array     CLOB,
    varchar_array CLOB
);

CREATE TABLE array_types_annotation_test (
    id                      INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    array_no_annotation     CLOB,
    array_jdbc_type         CLOB,
    array_type_handler      CLOB,
    array_number_special    CLOB,
    array_full_annotated    CLOB
);

CREATE TABLE test_special_types (
    id        INT NOT NULL PRIMARY KEY,
    json_map  CLOB,
    json_list CLOB,
    json_set  CLOB,
    int_array CLOB
);

CREATE TABLE binary_types_explicit_test (
    id                    INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    binary_value          VARBINARY(1000),
    varbinary_value       BLOB,
    longvarbinary_value   BLOB,
    blob_value            BLOB
);

CREATE TABLE enum_types_explicit_test (
    id               INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_string    VARCHAR(50),
    status_enum_code VARCHAR(50),
    status_ordinal   INT,
    status_code      INT
);

CREATE TABLE time_types_explicit_test (
    id                  INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_value          DATE,
    time_value          TIME,
    timestamp_value     TIMESTAMP,
    local_date_ts       TIMESTAMP,
    local_time_ts       TIMESTAMP,
    local_datetime_ts   TIMESTAMP,
    julian_day          BIGINT
);

CREATE TABLE json_types_explicit_test (
    id           INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    json_varchar CLOB,
    json_mysql   CLOB,
    nested_json  CLOB
);
