plugins {
    id 'java-library'
    id 'maven-publish'
    id 'antlr'
    id 'com.gradleup.shadow'
}

ext.pomName = 'dbVisitor Adapter of Redis'
description = 'JDBC driver adapter for Redis.'

configurations {
    shaded
}

dependencies {
    api project(':dbvisitor-driver')
    api 'redis.clients:jedis:6.1.0'

    antlr "org.antlr:antlr4:${property('lib.antlr')}"
    compileOnly "org.antlr:antlr4-runtime:${property('lib.antlr')}"
    shaded "org.antlr:antlr4-runtime:${property('lib.antlr')}"
    testImplementation "org.antlr:antlr4-runtime:${property('lib.antlr')}"
    testImplementation 'org.powermock:powermock-module-junit4:2.0.9'
    testImplementation 'org.powermock:powermock-api-mockito2:2.0.9'
}

tasks.named('generateGrammarSource') {
    arguments += ['-visitor', '-package', 'net.hasor.dbvisitor.adapter.redis.parser']
}

tasks.named('shadowJar') {
    configurations = [project.configurations.shaded]
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    relocate 'org.antlr', 'net.hasor.dbvisitor.adapter.redis.internal.jars.antlr'
    exclude 'META-INF/maven/ognl/**'
    exclude 'META-INF/maven/org.javassist/**'
}
